/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package areacalcgui.containers;

import areacalcgui.shapes.Triangle;
import java.awt.event.KeyEvent;
import utilities.Utilities;

/**
 *
 * @author omar
 */
public class TrianglePanel extends javax.swing.JPanel {

    /**
     * Creates new form TrianglePanel
     */
    public TrianglePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sideAInput = new javax.swing.JTextField();
        sideBInput = new javax.swing.JTextField();
        sideCInput = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        calcButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        areaText = new javax.swing.JLabel();
        perimeterText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 600));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 56, 56));
        jLabel1.setText("Triangle");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(56, 56, 56));
        jLabel2.setText("Side B :");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 56, 56));
        jLabel3.setText("Side C :");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(56, 56, 56));
        jLabel4.setText("Side A :");

        sideAInput.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        sideAInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sideAInputKeyTyped(evt);
            }
        });

        sideBInput.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        sideBInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sideBInputKeyTyped(evt);
            }
        });

        sideCInput.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        sideCInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sideCInputKeyTyped(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(200, 35, 51));
        errorLabel.setPreferredSize(new java.awt.Dimension(300, 21));

        calcButton.setBackground(new java.awt.Color(97, 218, 251));
        calcButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        calcButton.setText("Calculate");
        calcButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcButtonMouseClicked(evt);
            }
        });
        calcButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calcButtonKeyPressed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(97, 218, 251));
        clearButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });
        clearButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearButtonKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(56, 56, 56));
        jLabel6.setText("Area :");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(56, 56, 56));
        jLabel7.setText("Perimeter :");

        areaText.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        areaText.setForeground(new java.awt.Color(40, 44, 52));
        areaText.setText("0.0");

        perimeterText.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        perimeterText.setForeground(new java.awt.Color(40, 44, 52));
        perimeterText.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sideBInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sideAInput))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sideCInput)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(73, 73, 73))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(134, 134, 134)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areaText)
                            .addComponent(perimeterText))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(243, 243, 243))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sideAInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sideBInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sideCInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perimeterText))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private  void calculateFun() {
        Triangle triangle = new Triangle();
        
        // clear
        errorLabel.setText("");
        areaText.setText("0.0");
        perimeterText.setText("0.0");
        
        try {
            float sideAVal = Float.parseFloat(sideAInput.getText());
            float sideBVal = Float.parseFloat(sideBInput.getText());
            float sideCVal = Float.parseFloat(sideCInput.getText());
            
            triangle.setSide1(sideAVal);
            triangle.setSide2(sideBVal);
            triangle.setSide3(sideCVal);
            
            triangle.validate();
            triangle.validateTriangle();
            
            triangle.calcArea();
            triangle.calcPerimeter();
            
            areaText.setText(Float.toString(triangle.getArea()));
            perimeterText.setText(Float.toString(triangle.getPerimeter()));
            
        } catch(NumberFormatException err) {
            errorLabel.setText("Enter Valid Numbers!");
        } catch (ArithmeticException err) {
            errorLabel.setText(err.getMessage());
        }
    }
    
    private void clearAllFun() {
        errorLabel.setText("");
        sideAInput.setText("");
        sideBInput.setText("");
        sideCInput.setText("");
        areaText.setText("0.0");
        perimeterText.setText("0.0");
    }
    
    private void calcButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcButtonMouseClicked
        calculateFun();
    }//GEN-LAST:event_calcButtonMouseClicked
    
    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        clearAllFun();
    }//GEN-LAST:event_clearButtonMouseClicked

    private void sideAInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sideAInputKeyTyped
        Utilities.preventLetters(evt, errorLabel);
        Utilities.clearResults(areaText, perimeterText);
    }//GEN-LAST:event_sideAInputKeyTyped

    private void sideBInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sideBInputKeyTyped
        Utilities.preventLetters(evt, errorLabel);
        Utilities.clearResults(areaText, perimeterText);
    }//GEN-LAST:event_sideBInputKeyTyped

    private void sideCInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sideCInputKeyTyped
        Utilities.preventLetters(evt, errorLabel);
        Utilities.clearResults(areaText, perimeterText);
    }//GEN-LAST:event_sideCInputKeyTyped

    private void calcButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calcButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculateFun();
        }
    }//GEN-LAST:event_calcButtonKeyPressed

    private void clearButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            clearAllFun();
        }
    }//GEN-LAST:event_clearButtonKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaText;
    private javax.swing.JButton calcButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel perimeterText;
    private javax.swing.JTextField sideAInput;
    private javax.swing.JTextField sideBInput;
    private javax.swing.JTextField sideCInput;
    // End of variables declaration//GEN-END:variables
}
